name: Publish to NPM

on:
  push:
    branches: [main]
    paths:
      - 'packages/**'
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - run: npm ci
      - name: Build blogue-core first
        run: npm run build --workspace=packages/blogue-core
      - name: Build blogue-cli
        run: npm run build --workspace=packages/blogue-cli
      - run: npm run test
      - run: npm run lint

  publish:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      
      - run: npm ci
      - name: Build blogue-core first
        run: npm run build --workspace=packages/blogue-core
      - name: Build blogue-cli
        run: npm run build --workspace=packages/blogue-cli
      
      - name: Publish blogue-core
        run: cd packages/blogue-core && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Publish blogue CLI
        run: cd packages/blogue-cli && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}